# training params
buffer_size: 100000
buffer_size_debug: 128
batch_size: 256
total_steps: 1000000
repeats_per_buffer: 3
critic_update_multiplier: 1
actor_update_multiplier: 1
learning_rate: 0.0007
discount_factor: 0.95

# exploration settings
exploration_steps: 0

# SAC settings
use_entropy: true
target_entropy: null

# helper params
wandb_project: 'azheruddin_msc'
weights_directory: 'weights'
optim_weights_directory: 'optim_weights'
net_version: ''
net_number: 0
epoch_interval: 1
batch_interval: -1
